//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mynance.res.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mynance.res.localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string Administrator_Fullname {
            get {
                return ResourceManager.GetString("Administrator_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Administrator_IsActive {
            get {
                return ResourceManager.GetString("Administrator_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        internal static string Administrator_LastActive {
            get {
                return ResourceManager.GetString("Administrator_LastActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Portal.
        /// </summary>
        internal static string Administrator_PortalHeader {
            get {
                return ResourceManager.GetString("Administrator_PortalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        internal static string Administrator_RegistrationDate {
            get {
                return ResourceManager.GetString("Administrator_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Administrator_Username {
            get {
                return ResourceManager.GetString("Administrator_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        internal static string CategoryBills {
            get {
                return ResourceManager.GetString("CategoryBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groceries.
        /// </summary>
        internal static string CategoryGroceries {
            get {
                return ResourceManager.GetString("CategoryGroceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        internal static string CategoryLoans {
            get {
                return ResourceManager.GetString("CategoryLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string CategoryOther {
            get {
                return ResourceManager.GetString("CategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        internal static string CategorySubscriptions {
            get {
                return ResourceManager.GetString("CategorySubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string CategoryTotal {
            get {
                return ResourceManager.GetString("CategoryTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget for this month.
        /// </summary>
        internal static string Dashboard_CurrentBudget {
            get {
                return ResourceManager.GetString("Dashboard_CurrentBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit budget.
        /// </summary>
        internal static string Dashboard_EditBudget {
            get {
                return ResourceManager.GetString("Dashboard_EditBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendings.
        /// </summary>
        internal static string Dashboard_Spendings {
            get {
                return ResourceManager.GetString("Dashboard_Spendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LocaleEnglish {
            get {
                return ResourceManager.GetString("LocaleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        internal static string LocaleSerbian {
            get {
                return ResourceManager.GetString("LocaleSerbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Mynance!.
        /// </summary>
        internal static string LoginPage_Greeting {
            get {
                return ResourceManager.GetString("LoginPage_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account? Sign up here!.
        /// </summary>
        internal static string LoginPage_NoAccount {
            get {
                return ResourceManager.GetString("LoginPage_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPage_Password {
            get {
                return ResourceManager.GetString("LoginPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string LoginPage_SignIn {
            get {
                return ResourceManager.GetString("LoginPage_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginPage_Username {
            get {
                return ResourceManager.GetString("LoginPage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Navigator_Backward {
            get {
                return ResourceManager.GetString("Navigator_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        internal static string ProfilePage_BalanceStatus {
            get {
                return ResourceManager.GetString("ProfilePage_BalanceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string RegisterPage_Fullname {
            get {
                return ResourceManager.GetString("RegisterPage_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here!.
        /// </summary>
        internal static string RegisterPage_Header {
            get {
                return ResourceManager.GetString("RegisterPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterPage_Password {
            get {
                return ResourceManager.GetString("RegisterPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string RegisterPage_PasswordConfirm {
            get {
                return ResourceManager.GetString("RegisterPage_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string RegisterPage_Submit {
            get {
                return ResourceManager.GetString("RegisterPage_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string RegisterPage_Username {
            get {
                return ResourceManager.GetString("RegisterPage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string SideNavbar_Calendar {
            get {
                return ResourceManager.GetString("SideNavbar_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string SideNavbar_Dashboard {
            get {
                return ResourceManager.GetString("SideNavbar_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string SideNavbar_Greeting {
            get {
                return ResourceManager.GetString("SideNavbar_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SideNavbar_Logout {
            get {
                return ResourceManager.GetString("SideNavbar_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string SideNavbar_ProfileSettings {
            get {
                return ResourceManager.GetString("SideNavbar_ProfileSettings", resourceCulture);
            }
        }
    }
}
